[2024-01-03T07:57:56.382+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_process.get_data manual__2024-01-03T07:57:46.162443+00:00 [queued]>
[2024-01-03T07:57:56.481+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_process.get_data manual__2024-01-03T07:57:46.162443+00:00 [queued]>
[2024-01-03T07:57:56.481+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-03T07:57:56.619+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_data> on 2024-01-03 07:57:46.162443+00:00
[2024-01-03T07:57:56.693+0000] {standard_task_runner.py:60} INFO - Started process 583 to run task
[2024-01-03T07:57:56.704+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'job_process', 'get_data', 'manual__2024-01-03T07:57:46.162443+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/job_process.py', '--cfg-path', '/tmp/tmp3w0bh5iv']
[2024-01-03T07:57:56.760+0000] {standard_task_runner.py:88} INFO - Job 162: Subtask get_data
[2024-01-03T07:57:57.156+0000] {task_command.py:423} INFO - Running <TaskInstance: job_process.get_data manual__2024-01-03T07:57:46.162443+00:00 [running]> on host f01482236d7b
[2024-01-03T07:57:57.466+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='job_process' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T07:57:46.162443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-03T07:57:46.162443+00:00'
[2024-01-03T07:58:23.448+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/job_process.py", line 54, in get_data
    jobDescriptions = [description.text for description in browser.find_elements(By.XPATH,'//div[@class="info"]/span[@style="color: #5b5b5b;margin-top: 5px;"]')]
  File "/opt/airflow/dags/job_process.py", line 54, in <listcomp>
    jobDescriptions = [description.text for description in browser.find_elements(By.XPATH,'//div[@class="info"]/span[@style="color: #5b5b5b;margin-top: 5px;"]')]
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: target frame detached
  (failed to check if window was closed: disconnected: Unable to receive message from renderer)
  (Session info: headless chrome=119.0.6045.105)
Stacktrace:
#0 0x5575809405e3 <unknown>
#1 0x557580602f0d <unknown>
#2 0x5575805e8f4e <unknown>
#3 0x5575805e7481 <unknown>
#4 0x5575805e7e39 <unknown>
#5 0x5575805f88ac <unknown>
#6 0x5575806104c1 <unknown>
#7 0x55758061613b <unknown>
#8 0x5575805e85ce <unknown>
#9 0x557580610157 <unknown>
#10 0x557580693a48 <unknown>
#11 0x557580677cc3 <unknown>
#12 0x5575806430e4 <unknown>
#13 0x5575806440ae <unknown>
#14 0x557580906ce1 <unknown>
#15 0x55758090ab7e <unknown>
#16 0x5575808f44b5 <unknown>
#17 0x55758090b7d6 <unknown>
#18 0x5575808d7dbf <unknown>
#19 0x55758092e748 <unknown>
#20 0x55758092e917 <unknown>
#21 0x55758093f773 <unknown>
#22 0x7f0b7eb84044 <unknown>

[2024-01-03T07:58:23.649+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=job_process, task_id=get_data, execution_date=20240103T075746, start_date=20240103T075756, end_date=20240103T075823
[2024-01-03T07:58:23.799+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 162 for task get_data (Message: target frame detached
  (failed to check if window was closed: disconnected: Unable to receive message from renderer)
  (Session info: headless chrome=119.0.6045.105)
Stacktrace:
#0 0x5575809405e3 <unknown>
#1 0x557580602f0d <unknown>
#2 0x5575805e8f4e <unknown>
#3 0x5575805e7481 <unknown>
#4 0x5575805e7e39 <unknown>
#5 0x5575805f88ac <unknown>
#6 0x5575806104c1 <unknown>
#7 0x55758061613b <unknown>
#8 0x5575805e85ce <unknown>
#9 0x557580610157 <unknown>
#10 0x557580693a48 <unknown>
#11 0x557580677cc3 <unknown>
#12 0x5575806430e4 <unknown>
#13 0x5575806440ae <unknown>
#14 0x557580906ce1 <unknown>
#15 0x55758090ab7e <unknown>
#16 0x5575808f44b5 <unknown>
#17 0x55758090b7d6 <unknown>
#18 0x5575808d7dbf <unknown>
#19 0x55758092e748 <unknown>
#20 0x55758092e917 <unknown>
#21 0x55758093f773 <unknown>
#22 0x7f0b7eb84044 <unknown>
; 583)
[2024-01-03T07:58:23.905+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-03T07:58:24.074+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
